import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, 'dist');
const packageInfo = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));

async function filesIn(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? filesIn(path) : [path];
  }));
  return nested.flat();
}

const files = await filesIn(dist);
const precacheFiles = files
  .filter((file) => !file.endsWith(`${sep}sw.js`) && !file.endsWith('.map') && !file.endsWith('staticwebapp.config.json'))
  .filter((file) => /\.(?:html|css|js|webp|svg|webmanifest)$/u.test(file))
  .sort();

// Explicitly include every Vite-hashed script and stylesheet. The broader list
// also keeps the local legal pages, artwork, manifest, and icon usable offline.
const hashedAssets = precacheFiles.filter((file) => /[\\/]assets[\\/].*-[A-Za-z0-9_-]+\.(?:js|css)$/u.test(file));
if (hashedAssets.length === 0) throw new Error('No hashed Vite JavaScript or CSS assets found in dist.');

const precache = precacheFiles.map((file) => `/${relative(dist, file).split(sep).join('/')}`);
const fingerprint = createHash('sha256');
for (const file of precacheFiles) {
  fingerprint.update(relative(dist, file));
  fingerprint.update(await readFile(file));
}
const release = `${process.env.PWA_RELEASE_VERSION ?? packageInfo.version}-${fingerprint.digest('hex').slice(0, 12)}`;

const manifestPath = join(dist, 'manifest.webmanifest');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
manifest.start_url = `/?v=${encodeURIComponent(release)}`;
await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

const source = `/* Generated by scripts/generate-sw.mjs. Do not edit this release artifact. */
const RELEASE = ${JSON.stringify(release)};
const CACHE = \`rhythm-reader-\${RELEASE}\`;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith('rhythm-reader-') && name !== CACHE).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function offlineDocument(url) {
  const cache = await caches.open(CACHE);
  const pathname = url.pathname === '/' ? '/index.html' : (url.pathname.endsWith('/') ? \`\${url.pathname}index.html\` : url.pathname);
  return (await cache.match(pathname)) ?? cache.match('/index.html');
}

async function networkFirstNavigation(request) {
  try {
    return await fetch(request);
  } catch {
    const fallback = await offlineDocument(new URL(request.url));
    return fallback ?? new Response('Offline', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}

async function cacheFirstAsset(request) {
  // Module requests carry an Origin header while cache.addAll() does not. The
  // build artifact carries Vary: Origin, so ignore that transport-only variance.
  const cached = await caches.match(request, { ignoreVary: true });
  if (cached) return cached;
  const response = await fetch(request);
  const url = new URL(request.url);
  if (url.pathname.startsWith('/assets/') && (response.headers.get('content-type') || '').includes('text/html')) {
    return new Response('Asset not found', { status: 404, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
  return response;
}

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (event.request.mode === 'navigate') {
    event.respondWith(networkFirstNavigation(event.request));
    return;
  }
  // Assets either resolve to their own cached response or fail normally. HTML
  // is deliberately never used as an asset fallback, which preserves module MIME.
  event.respondWith(cacheFirstAsset(event.request));
});
`;

await writeFile(join(dist, 'sw.js'), source);
console.log(`Generated dist/sw.js for release ${release} with ${precache.length} precached files (${hashedAssets.length} hashed JS/CSS assets).`);
